name: 'Setup Environment'
description: 'Composite action to setup development environment with Node.js and dependencies'
author: 'Suspect Software'

inputs:
  node-version:
    description: 'Node.js version to install'
    required: false
    default: '18'
  cache-dependency-path:
    description: 'Path to package-lock.json or yarn.lock for caching'
    required: false
    default: 'package-lock.json'
  install-dependencies:
    description: 'Whether to install dependencies'
    required: false
    default: 'true'

outputs:
  node-version:
    description: 'The Node.js version that was installed'
    value: ${{ steps.setup-node.outputs.node-version }}
  cache-hit:
    description: 'Whether dependencies were restored from cache'
    value: ${{ steps.setup-node.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
    
    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      run: |
        if [ -f "package.json" ]; then
          echo "Installing dependencies..."
          npm ci
        else
          echo "No package.json found, skipping dependency installation"
        fi
    
    - name: Print environment info
      shell: bash
      run: |
        echo "Node.js version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Working directory: $(pwd)"
