name: Go Build and Test
description: Composite action to build and test a Go project

inputs:
  test-command:
    description: Command to run Go tests
    required: false
    default: go test ./... -v

outputs:
  test-status:
    description: Status of the test step
    value: ${{ steps.test.outcome }}

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.24'

    - name: Run tests
      id: test
      shell: bash
      run: ${{ inputs.test-command }}

    - name: Build summary
      shell: bash
      run: |
        echo "### Go Test Summary" >> $GITHUB_STEP_SUMMARY
        echo "- Test Status: ${{ steps.test.outcome }}" >> $GITHUB_STEP_SUMMARY
