name: Go Build and Test
description: Composite action to build and test a Go project

outputs:
  build-status:
    description: Status of the build step
    value: ${{ steps.build.outcome }}
    

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.24'

    - name: Build project
      id: build
      shell: bash
      run: |
        go build -o main .
        ls -lla

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      if: ${{ github.event_name != 'pull_request' }}
      with:
        name: artifact
        path: main

    - name: Build summary
      shell: bash
      run: |
        echo "### Go Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- Build Status: ${{ steps.build.outcome }}" >> $GITHUB_STEP_SUMMARY
