name: Go Build and Test
description: Composite action to build and test a Go project

inputs:
  build-command:
    description: Command to build the Go project
    required: false
    default: go build ./...

outputs:
  build-status:
    description: Status of the build step
    value: ${{ steps.build.outcome }}

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.24'

    - name: Build project
      id: build
      shell: bash
      run: |
        echo "Building project with command: ${{ inputs.build-command }}"
        ${{ inputs.build-command }}

    - name: Build summary
      shell: bash
      run: |
        echo "### Go Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- Build Status: ${{ steps.build.outcome }}" >> $GITHUB_STEP_SUMMARY
        if [[ "${{ inputs.upload-coverage }}" == "true" ]]; then
          echo "- Coverage File: ${{ inputs.coverage-file }}" >> $GITHUB_STEP_SUMMARY
        fi
